// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor.models;

import com.azure.ai.metricsadvisor.implementation.util.Option;
import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;
import java.util.UUID;

/** The AnomalyAlertingConfigurationPatch model. */
@Fluent
public final class AnomalyAlertingConfigurationPatch {
    /*
     * Anomaly alerting configuration name
     */
    @JsonProperty(value = "name")
    private Option<String> name;

    /*
     * anomaly alerting configuration description
     */
    @JsonProperty(value = "description")
    private Option<String> description;

    /*
     * cross metrics operator
     */
    @JsonProperty(value = "crossMetricsOperator")
    private Option<MetricAnomalyAlertConfigurationsOperator> crossMetricsOperator;

    /*
     * dimensions used to split alert
     */
    @JsonProperty(value = "splitAlertByDimensions")
    private Option<List<String>> splitAlertByDimensions;

    /*
     * hook unique ids
     */
    @JsonProperty(value = "hookIds")
    private Option<List<UUID>> hookIds;

    /*
     * Anomaly alerting configurations
     */
    @JsonProperty(value = "metricAlertingConfigurations")
    private Option<List<MetricAlertingConfiguration>> metricAlertingConfigurations;

    /**
     * Get the name property: Anomaly alerting configuration name.
     *
     * @return the name value.
     */
    String getName() {
        if (this.name != null) {
            this.name.getValue();
        }
        return null;
    }

    /**
     * Set the name property: Anomaly alerting configuration name.
     *
     * @param name the name value to set.
     * @return the AnomalyAlertingConfigurationPatch object itself.
     */
    public AnomalyAlertingConfigurationPatch setName(String name) {
        if (name == null) {
            this.name = Option.empty();
        } else {
            this.name = Option.of(name);
        }
        return this;
    }

    /**
     * Get the description property: anomaly alerting configuration description.
     *
     * @return the description value.
     */
    String getDescription() {
        if (this.description != null) {
            this.description.getValue();
        }
        return null;
    }

    /**
     * Set the description property: anomaly alerting configuration description.
     *
     * @param description the description value to set.
     * @return the AnomalyAlertingConfigurationPatch object itself.
     */
    public AnomalyAlertingConfigurationPatch setDescription(String description) {
        if (description == null) {
            this.description = Option.empty();
        } else {
            this.description = Option.of(description);
        }
        return this;
    }

    /**
     * Get the crossMetricsOperator property: cross metrics operator.
     *
     * @return the crossMetricsOperator value.
     */
    MetricAnomalyAlertConfigurationsOperator getCrossMetricsOperator() {
        if (this.crossMetricsOperator != null) {
            this.crossMetricsOperator.getValue();
        }
        return null;
    }

    /**
     * Set the crossMetricsOperator property: cross metrics operator.
     *
     * @param crossMetricsOperator the crossMetricsOperator value to set.
     * @return the AnomalyAlertingConfigurationPatch object itself.
     */
    public AnomalyAlertingConfigurationPatch setCrossMetricsOperator(
        MetricAnomalyAlertConfigurationsOperator crossMetricsOperator) {
        if (crossMetricsOperator == null) {
            this.crossMetricsOperator = Option.empty();
        } else {
            this.crossMetricsOperator = Option.of(crossMetricsOperator);
        }
        return this;
    }

    /**
     * Get the splitAlertByDimensions property: dimensions used to split alert.
     *
     * @return the splitAlertByDimensions value.
     */
    List<String> getSplitAlertByDimensions() {
        if (this.splitAlertByDimensions != null) {
            this.splitAlertByDimensions.getValue();
        }
        return null;
    }

    /**
     * Set the splitAlertByDimensions property: dimensions used to split alert.
     *
     * @param splitAlertByDimensions the splitAlertByDimensions value to set.
     * @return the AnomalyAlertingConfigurationPatch object itself.
     */
    public AnomalyAlertingConfigurationPatch setSplitAlertByDimensions(List<String> splitAlertByDimensions) {
        if (splitAlertByDimensions == null) {
            this.splitAlertByDimensions = Option.empty();
        } else {
            this.splitAlertByDimensions = Option.of(splitAlertByDimensions);
        }
        return this;
    }

    /**
     * Get the hookIds property: hook unique ids.
     *
     * @return the hookIds value.
     */
    List<UUID> getHookIds() {
        if (this.hookIds != null) {
            this.hookIds.getValue();
        }
        return null;
    }

    /**
     * Set the hookIds property: hook unique ids.
     *
     * @param hookIds the hookIds value to set.
     * @return the AnomalyAlertingConfigurationPatch object itself.
     */
    public AnomalyAlertingConfigurationPatch setHookIds(List<UUID> hookIds) {
        if (hookIds == null) {
            this.hookIds = Option.empty();
        } else {
            this.hookIds = Option.of(hookIds);
        }
        return this;
    }

    /**
     * Get the metricAlertingConfigurations property: Anomaly alerting configurations.
     *
     * @return the metricAlertingConfigurations value.
     */
    List<MetricAlertingConfiguration> getMetricAlertingConfigurations() {
        if (this.metricAlertingConfigurations != null) {
            this.metricAlertingConfigurations.getValue();
        }
        return null;
    }

    /**
     * Set the metricAlertingConfigurations property: Anomaly alerting configurations.
     *
     * @param metricAlertingConfigurations the metricAlertingConfigurations value to set.
     * @return the AnomalyAlertingConfigurationPatch object itself.
     */
    public AnomalyAlertingConfigurationPatch setMetricAlertingConfigurations(
            List<MetricAlertingConfiguration> metricAlertingConfigurations) {
        if (metricAlertingConfigurations == null) {
            this.metricAlertingConfigurations = Option.empty();
        } else {
            this.metricAlertingConfigurations = Option.of(metricAlertingConfigurations);
        }
        return this;
    }
}
