// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor.models;

import com.azure.ai.metricsadvisor.implementation.util.Option;
import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The AzureSQLConnectionStringParamPatch model. */
@Fluent
public final class AzureSQLConnectionStringParameterPatch {
    /*
     * The connection string to access the Azure SQL.
     */
    @JsonProperty(value = "connectionString")
    private Option<String> connectionString;

    /**
     * Get the connectionString property: The connection string to access the Azure SQL.
     *
     * @return the connectionString value.
     */
    String getConnectionString() {
        if (this.connectionString != null) {
            this.connectionString.getValue();
        }
        return null;
    }

    /**
     * Set the connectionString property: The connection string to access the Azure SQL.
     *
     * @param connectionString the connectionString value to set.
     * @return the AzureSQLConnectionStringParamPatch object itself.
     */
    public AzureSQLConnectionStringParameterPatch setConnectionString(String connectionString) {
        if (connectionString == null) {
            this.connectionString = Option.empty();
        } else {
            this.connectionString = Option.of(connectionString);
        }
        return this;
    }
}
