// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor.models;

import com.azure.ai.metricsadvisor.implementation.util.Option;
import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The AzureDataLakeStorageGen2ParameterPatch model. */
@Fluent
public final class AzureDataLakeStorageGen2ParameterPatch {
    /*
     * The account name of this Azure Data Lake
     */
    @JsonProperty(value = "accountName")
    private Option<String> accountName;

    /*
     * The account key that can access this Azure Data Lake
     */
    @JsonProperty(value = "accountKey")
    private Option<String> accountKey;

    /*
     * The file system (container) name in this Azure Data Lake
     */
    @JsonProperty(value = "fileSystemName")
    private Option<String> fileSystemName;

    /*
     * The directory template under this file system
     */
    @JsonProperty(value = "directoryTemplate")
    private Option<String> directoryTemplate;

    /*
     * The file template
     */
    @JsonProperty(value = "fileTemplate")
    private Option<String> fileTemplate;

    /**
     * Get the accountName property: The account name of this Azure Data Lake.
     *
     * @return the accountName value.
     */
    String getAccountName() {
        if (this.accountName != null) {
            this.accountName.getValue();
        }
        return null;
    }

    /**
     * Set the accountName property: The account name of this Azure Data Lake.
     *
     * @param accountName the accountName value to set.
     * @return the AzureDataLakeStorageGen2ParameterPatch object itself.
     */
    public AzureDataLakeStorageGen2ParameterPatch setAccountName(String accountName) {
        if (accountName == null) {
            this.accountName = Option.empty();
        } else {
            this.accountName = Option.of(accountName);
        }
        return this;
    }

    /**
     * Get the accountKey property: The account key that can access this Azure Data Lake.
     *
     * @return the accountKey value.
     */
    String getAccountKey() {
        if (this.accountKey != null) {
            this.accountKey.getValue();
        }
        return null;
    }

    /**
     * Set the accountKey property: The account key that can access this Azure Data Lake.
     *
     * @param accountKey the accountKey value to set.
     * @return the AzureDataLakeStorageGen2ParameterPatch object itself.
     */
    public AzureDataLakeStorageGen2ParameterPatch setAccountKey(String accountKey) {
        if (accountKey == null) {
            this.accountKey = Option.empty();
        } else {
            this.accountKey = Option.of(accountKey);
        }
        return this;
    }

    /**
     * Get the fileSystemName property: The file system (container) name in this Azure Data Lake.
     *
     * @return the fileSystemName value.
     */
    String getFileSystemName() {
        if (this.fileSystemName != null) {
            this.fileSystemName.getValue();
        }
        return null;
    }

    /**
     * Set the fileSystemName property: The file system (container) name in this Azure Data Lake.
     *
     * @param fileSystemName the fileSystemName value to set.
     * @return the AzureDataLakeStorageGen2ParameterPatch object itself.
     */
    public AzureDataLakeStorageGen2ParameterPatch setFileSystemName(String fileSystemName) {
        if (fileSystemName == null) {
            this.fileSystemName = Option.empty();
        } else {
            this.fileSystemName = Option.of(fileSystemName);
        }
        return this;
    }

    /**
     * Get the directoryTemplate property: The directory template under this file system.
     *
     * @return the directoryTemplate value.
     */
    String getDirectoryTemplate() {
        if (this.directoryTemplate != null) {
            this.directoryTemplate.getValue();
        }
        return null;
    }

    /**
     * Set the directoryTemplate property: The directory template under this file system.
     *
     * @param directoryTemplate the directoryTemplate value to set.
     * @return the AzureDataLakeStorageGen2ParameterPatch object itself.
     */
    public AzureDataLakeStorageGen2ParameterPatch setDirectoryTemplate(String directoryTemplate) {
        if (directoryTemplate == null) {
            this.directoryTemplate = Option.empty();
        } else {
            this.directoryTemplate = Option.of(directoryTemplate);
        }
        return this;
    }

    /**
     * Get the fileTemplate property: The file template.
     *
     * @return the fileTemplate value.
     */
    String getFileTemplate() {
        if (this.fileTemplate != null) {
            this.fileTemplate.getValue();
        }
        return null;
    }

    /**
     * Set the fileTemplate property: The file template.
     *
     * @param fileTemplate the fileTemplate value to set.
     * @return the AzureDataLakeStorageGen2ParameterPatch object itself.
     */
    public AzureDataLakeStorageGen2ParameterPatch setFileTemplate(String fileTemplate) {
        if (fileTemplate == null) {
            this.fileTemplate = Option.empty();
        } else {
            this.fileTemplate = Option.of(fileTemplate);
        }
        return this;
    }
}
