// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor.models;

/**
 * A type representing blob connection string.
 */
public final class AzureBlobDataSourceConnectionString {
    private final String rawConnectionString;
    private final CredentialType credentialType;

    /**
     * Gets the raw connection string.
     *
     * @return The raw connection string
     */
    public String getValue() {
        return this.rawConnectionString;
    }

    /**
     * Gets the credential type used for the connection string.
     *
     * @return The credential type.
     */
    public CredentialType getCredentialType() {
        return this.credentialType;
    }

    /**
     * Creates a {@link AzureBlobDataSourceConnectionString} that uses the credential encoded in the given
     * {@code connectionString} for authentication.
     *
     * @param connectionString The connection string with credential encoded
     * @return The {@link AzureBlobDataSourceConnectionString}
     */
    public static AzureBlobDataSourceConnectionString withBasicCredential(String connectionString) {
        return new AzureBlobDataSourceConnectionString(connectionString, CredentialType.BASIC);
    }

    /**
     * Creates a {@link AzureBlobDataSourceConnectionString} that uses managed identity for authentication.
     *
     * @param connectionString The connection string
     * @return The {@link AzureBlobDataSourceConnectionString}
     */
    public static AzureBlobDataSourceConnectionString withManagedIdentityCredential(String connectionString) {
        return new AzureBlobDataSourceConnectionString(connectionString,
            CredentialType.MANAGED_IDENTITY);
    }

    private AzureBlobDataSourceConnectionString(String connectionString,
                                                CredentialType credentialType) {
        this.rawConnectionString = connectionString;
        this.credentialType = credentialType;
    }
}
