// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor.models;

import com.azure.ai.metricsadvisor.implementation.util.Option;
import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The ChangeThresholdConditionPatch model. */
@Fluent
public final class ChangeThresholdConditionPatch {
    /*
     * change percentage, value range : [0, +∞)
     */
    @JsonProperty(value = "changePercentage")
    private Option<Double> changePercentage;

    /*
     * shift point, value range : [1, +∞)
     */
    @JsonProperty(value = "shiftPoint")
    private Option<Integer> shiftPoint;

    /*
     * if the withinRange = true, detected data is abnormal when the value
     * falls in the range, in this case anomalyDetectorDirection must be Both
     * if the withinRange = false, detected data is abnormal when the value
     * falls out of the range
     */
    @JsonProperty(value = "withinRange")
    private Option<Boolean> withinRange;

    /*
     * detection direction
     */
    @JsonProperty(value = "anomalyDetectorDirection")
    private Option<AnomalyDetectorDirection> anomalyDetectorDirection;

    /*
     * The suppressCondition property.
     */
    @JsonProperty(value = "suppressCondition")
    private Option<SuppressConditionPatch> suppressCondition;

    /**
     * Get the changePercentage property: change percentage, value range : [0, +∞).
     *
     * @return the changePercentage value.
     */
    Double getChangePercentage() {
        if (this.changePercentage != null) {
            this.changePercentage.getValue();
        }
        return null;
    }

    /**
     * Set the changePercentage property: change percentage, value range : [0, +∞).
     *
     * @param changePercentage the changePercentage value to set.
     * @return the ChangeThresholdConditionPatch object itself.
     */
    public ChangeThresholdConditionPatch setChangePercentage(Double changePercentage) {
        if (changePercentage == null) {
            this.changePercentage = Option.empty();
        } else {
            this.changePercentage = Option.of(changePercentage);
        }
        return this;
    }

    /**
     * Get the shiftPoint property: shift point, value range : [1, +∞).
     *
     * @return the shiftPoint value.
     */
    Integer getShiftPoint() {
        if (this.shiftPoint != null) {
            this.shiftPoint.getValue();
        }
        return null;
    }

    /**
     * Set the shiftPoint property: shift point, value range : [1, +∞).
     *
     * @param shiftPoint the shiftPoint value to set.
     * @return the ChangeThresholdConditionPatch object itself.
     */
    public ChangeThresholdConditionPatch setShiftPoint(Integer shiftPoint) {
        if (shiftPoint == null) {
            this.shiftPoint = Option.empty();
        } else {
            this.shiftPoint = Option.of(shiftPoint);
        }
        return this;
    }

    /**
     * Get the withinRange property: if the withinRange = true, detected data is abnormal when the value falls in the
     * range, in this case anomalyDetectorDirection must be Both if the withinRange = false, detected data is abnormal
     * when the value falls out of the range.
     *
     * @return the withinRange value.
     */
    Boolean isWithinRange() {
        if (this.withinRange != null) {
            this.withinRange.getValue();
        }
        return null;
    }

    /**
     * Set the withinRange property: if the withinRange = true, detected data is abnormal when the value falls in the
     * range, in this case anomalyDetectorDirection must be Both if the withinRange = false, detected data is abnormal
     * when the value falls out of the range.
     *
     * @param withinRange the withinRange value to set.
     * @return the ChangeThresholdConditionPatch object itself.
     */
    public ChangeThresholdConditionPatch setWithinRange(Boolean withinRange) {
        if (withinRange == null) {
            this.withinRange = Option.empty();
        } else {
            this.withinRange = Option.of(withinRange);
        }
        return this;
    }

    /**
     * Get the anomalyDetectorDirection property: detection direction.
     *
     * @return the anomalyDetectorDirection value.
     */
    AnomalyDetectorDirection getAnomalyDetectorDirection() {
        if (this.anomalyDetectorDirection != null) {
            this.anomalyDetectorDirection.getValue();
        }
        return null;
    }

    /**
     * Set the anomalyDetectorDirection property: detection direction.
     *
     * @param anomalyDetectorDirection the anomalyDetectorDirection value to set.
     * @return the ChangeThresholdConditionPatch object itself.
     */
    public ChangeThresholdConditionPatch setAnomalyDetectorDirection(
            AnomalyDetectorDirection anomalyDetectorDirection) {
        if (anomalyDetectorDirection == null) {
            this.anomalyDetectorDirection = Option.empty();
        } else {
            this.anomalyDetectorDirection = Option.of(anomalyDetectorDirection);
        }
        return this;
    }

    /**
     * Get the suppressCondition property: The suppressCondition property.
     *
     * @return the suppressCondition value.
     */
    SuppressConditionPatch getSuppressCondition() {
        if (this.suppressCondition != null) {
            this.suppressCondition.getValue();
        }
        return null;
    }

    /**
     * Set the suppressCondition property: The suppressCondition property.
     *
     * @param suppressCondition the suppressCondition value to set.
     * @return the ChangeThresholdConditionPatch object itself.
     */
    public ChangeThresholdConditionPatch setSuppressCondition(SuppressConditionPatch suppressCondition) {
        if (suppressCondition == null) {
            this.suppressCondition = Option.empty();
        } else {
            this.suppressCondition = Option.of(suppressCondition);
        }
        return this;
    }
}
