// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor.models;

/**
 * The data source credential types
 */
public enum CredentialType {
    /**
     * The basic credential
     */
    BASIC("Basic"),
    /**
     * The managed identity credentials
     */
    MANAGED_IDENTITY("ManagedIdentity"),
    /**
     * The sql connection string credentials
     */
    SQL_CONNECTION_STRING("AzureSQLConnectionString"),
    /**
     * The datalake shared key credentials
     */
    DATA_LAKE_GEN2_SHARED_KEY("DataLakeGen2SharedKey"),
    /**
     * The service principal credentials
     */
    SERVICE_PRINCIPAL("ServicePrincipal"),
    /**
     * The service principal in keyvault credentials
     */
    SERVICE_PRINCIPAL_IN_KV("ServicePrincipalInKV");

    private final String value;

    CredentialType(final String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return this.value;
    }
}
