// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor.models;

/**
 * The shared key credential entity for DataLakeGen2.
 */
public final class DataLakeGen2SharedKeyCredentialEntity extends DataSourceCredentialEntity {
    @Override
    public String getId() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }

    /**
     * Creates DataLakeGen2SharedKeyCredentialEntity.
     *
     * @param name The name
     * @param sharedKey The shared key
     */
    public DataLakeGen2SharedKeyCredentialEntity(String name, String sharedKey) {
    }

    /**
     * Sets the name.
     *
     * @param name The name
     * @return an updated object with name set
     */
    public DataLakeGen2SharedKeyCredentialEntity setName(String name) {
        return this;
    }

    /**
     * Sets the shared key,
     *
     * @param sharedKey The shared key
     * @returnan an updated object with shared key set
     */
    public DataLakeGen2SharedKeyCredentialEntity setSharedKey(String sharedKey) {
        return this;
    }

    /**
     * Sets the description.
     *
     * @param description The description.
     * @return an updated object with description set
     */
    public DataLakeGen2SharedKeyCredentialEntity setDescription(String description) {
        return this;
    }
}
