// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor.models;

import com.azure.ai.metricsadvisor.implementation.util.Option;
import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** The ServicePrincipalCredentialPatch model. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "dataSourceCredentialType")
@JsonTypeName("ServicePrincipal")
@Fluent
public final class DatasourceServicePrincipalPatch extends DatasourceCredentialEntityPatch {
    /*
     * The parameters property.
     */
    @JsonProperty(value = "parameters")
    private Option<ServicePrincipalParameterPatch> parameters;

    /**
     * Get the parameters property: The parameters property.
     *
     * @return the parameters value.
     */
    ServicePrincipalParameterPatch getParameters() {
        if (this.parameters != null) {
            this.parameters.getValue();
        }
        return null;
    }

    /**
     * Set the parameters property: The parameters property.
     *
     * @param parameters the parameters value to set.
     * @return the ServicePrincipalCredentialPatch object itself.
     */
    public DatasourceServicePrincipalPatch setParameters(ServicePrincipalParameterPatch parameters) {
        if (parameters == null) {
            this.parameters = Option.empty();
        } else {
            this.parameters = Option.of(parameters);
        }
        return this;
    }
}
