// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor.models;

import com.azure.ai.metricsadvisor.implementation.util.Option;
import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The InfluxDBParameterPatch model. */
@Fluent
public final class InfluxDBParameterPatch {
    /*
     * The connection string of this InfluxDB
     */
    @JsonProperty(value = "connectionString")
    private Option<String> connectionString;

    /*
     * A database name
     */
    @JsonProperty(value = "database")
    private Option<String> database;

    /*
     * The user name of the account that can access this database
     */
    @JsonProperty(value = "userName")
    private Option<String> userName;

    /*
     * The password of the account that can access this database
     */
    @JsonProperty(value = "password")
    private Option<String> password;

    /*
     * The script to query this database
     */
    @JsonProperty(value = "query")
    private Option<String> query;

    /**
     * Get the connectionString property: The connection string of this InfluxDB.
     *
     * @return the connectionString value.
     */
    String getConnectionString() {
        if (this.connectionString != null) {
            this.connectionString.getValue();
        }
        return null;
    }

    /**
     * Set the connectionString property: The connection string of this InfluxDB.
     *
     * @param connectionString the connectionString value to set.
     * @return the InfluxDBParameterPatch object itself.
     */
    public InfluxDBParameterPatch setConnectionString(String connectionString) {
        if (connectionString == null) {
            this.connectionString = Option.empty();
        } else {
            this.connectionString = Option.of(connectionString);
        }
        return this;
    }

    /**
     * Get the database property: A database name.
     *
     * @return the database value.
     */
    String getDatabase() {
        if (this.database != null) {
            this.database.getValue();
        }
        return null;
    }

    /**
     * Set the database property: A database name.
     *
     * @param database the database value to set.
     * @return the InfluxDBParameterPatch object itself.
     */
    public InfluxDBParameterPatch setDatabase(String database) {
        if (database == null) {
            this.database = Option.empty();
        } else {
            this.database = Option.of(database);
        }
        return this;
    }

    /**
     * Get the userName property: The user name of the account that can access this database.
     *
     * @return the userName value.
     */
    String getUserName() {
        if (this.userName != null) {
            this.userName.getValue();
        }
        return null;
    }

    /**
     * Set the userName property: The user name of the account that can access this database.
     *
     * @param userName the userName value to set.
     * @return the InfluxDBParameterPatch object itself.
     */
    public InfluxDBParameterPatch setUserName(String userName) {
        if (userName == null) {
            this.userName = Option.empty();
        } else {
            this.userName = Option.of(userName);
        }
        return this;
    }

    /**
     * Get the password property: The password of the account that can access this database.
     *
     * @return the password value.
     */
    String getPassword() {
        if (this.password != null) {
            this.password.getValue();
        }
        return null;
    }

    /**
     * Set the password property: The password of the account that can access this database.
     *
     * @param password the password value to set.
     * @return the InfluxDBParameterPatch object itself.
     */
    public InfluxDBParameterPatch setPassword(String password) {
        if (password == null) {
            this.password = Option.empty();
        } else {
            this.password = Option.of(password);
        }
        return this;
    }

    /**
     * Get the query property: The script to query this database.
     *
     * @return the query value.
     */
    String getQuery() {
        if (this.query != null) {
            this.query.getValue();
        }
        return null;
    }

    /**
     * Set the query property: The script to query this database.
     *
     * @param query the query value to set.
     * @return the InfluxDBParameterPatch object itself.
     */
    public InfluxDBParameterPatch setQuery(String query) {
        if (query == null) {
            this.query = Option.empty();
        } else {
            this.query = Option.of(query);
        }
        return this;
    }
}
