// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor.models;

import com.azure.ai.metricsadvisor.implementation.util.Option;
import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The ServicePrincipalInKVParamPatch model. */
@Fluent
public final class ServicePrincipalInKVParamPatch {
    /*
     * The Key Vault endpoint that storing the service principal.
     */
    @JsonProperty(value = "keyVaultEndpoint")
    private Option<String> keyVaultEndpoint;

    /*
     * The Client Id to access the Key Vault.
     */
    @JsonProperty(value = "keyVaultClientId")
    private Option<String> keyVaultClientId;

    /*
     * The Client Secret to access the Key Vault.
     */
    @JsonProperty(value = "keyVaultClientSecret")
    private Option<String> keyVaultClientSecret;

    /*
     * The secret name of the service principal's client Id in the Key Vault.
     */
    @JsonProperty(value = "servicePrincipalIdNameInKV")
    private Option<String> servicePrincipalIdNameInKV;

    /*
     * The secret name of the service principal's client secret in the Key
     * Vault.
     */
    @JsonProperty(value = "servicePrincipalSecretNameInKV")
    private Option<String> servicePrincipalSecretNameInKV;

    /*
     * The tenant id of your service principal.
     */
    @JsonProperty(value = "tenantId")
    private Option<String> tenantId;

    /**
     * Get the keyVaultEndpoint property: The Key Vault endpoint that storing the service principal.
     *
     * @return the keyVaultEndpoint value.
     */
    String getKeyVaultEndpoint() {
        if (this.keyVaultEndpoint != null) {
            this.keyVaultEndpoint.getValue();
        }
        return null;
    }

    /**
     * Set the keyVaultEndpoint property: The Key Vault endpoint that storing the service principal.
     *
     * @param keyVaultEndpoint the keyVaultEndpoint value to set.
     * @return the ServicePrincipalInKVParamPatch object itself.
     */
    public ServicePrincipalInKVParamPatch setKeyVaultEndpoint(String keyVaultEndpoint) {
        if (keyVaultEndpoint == null) {
            this.keyVaultEndpoint = Option.empty();
        } else {
            this.keyVaultEndpoint = Option.of(keyVaultEndpoint);
        }
        return this;
    }

    /**
     * Get the keyVaultClientId property: The Client Id to access the Key Vault.
     *
     * @return the keyVaultClientId value.
     */
    String getKeyVaultClientId() {
        if (this.keyVaultClientId != null) {
            this.keyVaultClientId.getValue();
        }
        return null;
    }

    /**
     * Set the keyVaultClientId property: The Client Id to access the Key Vault.
     *
     * @param keyVaultClientId the keyVaultClientId value to set.
     * @return the ServicePrincipalInKVParamPatch object itself.
     */
    public ServicePrincipalInKVParamPatch setKeyVaultClientId(String keyVaultClientId) {
        if (keyVaultClientId == null) {
            this.keyVaultClientId = Option.empty();
        } else {
            this.keyVaultClientId = Option.of(keyVaultClientId);
        }
        return this;
    }

    /**
     * Get the keyVaultClientSecret property: The Client Secret to access the Key Vault.
     *
     * @return the keyVaultClientSecret value.
     */
    String getKeyVaultClientSecret() {
        if (this.keyVaultClientSecret != null) {
            this.keyVaultClientSecret.getValue();
        }
        return null;
    }

    /**
     * Set the keyVaultClientSecret property: The Client Secret to access the Key Vault.
     *
     * @param keyVaultClientSecret the keyVaultClientSecret value to set.
     * @return the ServicePrincipalInKVParamPatch object itself.
     */
    public ServicePrincipalInKVParamPatch setKeyVaultClientSecret(String keyVaultClientSecret) {
        if (keyVaultClientSecret == null) {
            this.keyVaultClientSecret = Option.empty();
        } else {
            this.keyVaultClientSecret = Option.of(keyVaultClientSecret);
        }
        return this;
    }

    /**
     * Get the servicePrincipalIdNameInKV property: The secret name of the service principal's client Id in the Key
     * Vault.
     *
     * @return the servicePrincipalIdNameInKV value.
     */
    String getServicePrincipalIdNameInKV() {
        if (this.servicePrincipalIdNameInKV != null) {
            this.servicePrincipalIdNameInKV.getValue();
        }
        return null;
    }

    /**
     * Set the servicePrincipalIdNameInKV property: The secret name of the service principal's client Id in the Key
     * Vault.
     *
     * @param servicePrincipalIdNameInKV the servicePrincipalIdNameInKV value to set.
     * @return the ServicePrincipalInKVParamPatch object itself.
     */
    public ServicePrincipalInKVParamPatch setServicePrincipalIdNameInKV(String servicePrincipalIdNameInKV) {
        if (servicePrincipalIdNameInKV == null) {
            this.servicePrincipalIdNameInKV = Option.empty();
        } else {
            this.servicePrincipalIdNameInKV = Option.of(servicePrincipalIdNameInKV);
        }
        return this;
    }

    /**
     * Get the servicePrincipalSecretNameInKV property: The secret name of the service principal's client secret in the
     * Key Vault.
     *
     * @return the servicePrincipalSecretNameInKV value.
     */
    String getServicePrincipalSecretNameInKV() {
        if (this.servicePrincipalSecretNameInKV != null) {
            this.servicePrincipalSecretNameInKV.getValue();
        }
        return null;
    }

    /**
     * Set the servicePrincipalSecretNameInKV property: The secret name of the service principal's client secret in the
     * Key Vault.
     *
     * @param servicePrincipalSecretNameInKV the servicePrincipalSecretNameInKV value to set.
     * @return the ServicePrincipalInKVParamPatch object itself.
     */
    public ServicePrincipalInKVParamPatch setServicePrincipalSecretNameInKV(String servicePrincipalSecretNameInKV) {
        if (servicePrincipalSecretNameInKV == null) {
            this.servicePrincipalSecretNameInKV = Option.empty();
        } else {
            this.servicePrincipalSecretNameInKV = Option.of(servicePrincipalSecretNameInKV);
        }
        return this;
    }

    /**
     * Get the tenantId property: The tenant id of your service principal.
     *
     * @return the tenantId value.
     */
    String getTenantId() {
        if (this.tenantId != null) {
            this.tenantId.getValue();
        }
        return null;
    }

    /**
     * Set the tenantId property: The tenant id of your service principal.
     *
     * @param tenantId the tenantId value to set.
     * @return the ServicePrincipalInKVParamPatch object itself.
     */
    public ServicePrincipalInKVParamPatch setTenantId(String tenantId) {
        if (tenantId == null) {
            this.tenantId = Option.empty();
        } else {
            this.tenantId = Option.of(tenantId);
        }
        return this;
    }
}
