// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor.models;

/**
 * The service principal in key vault credential entity for data source..
 */
public final class ServicePrincipalInKeyVaultCredentialEntity extends DataSourceCredentialEntity {
    @Override
    public String getId() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }

    /**
     * Sets the name.
     *
     * @param name The name
     * @return an updated object with name set
     */
    public ServicePrincipalInKeyVaultCredentialEntity setName(String name) {
        return this;
    }

    /**
     * Sets the keyVault containing the data source secrets.
     *
     * @param keyVaultEndpoint The keyVault endpoint
     * @param keyVaultClientId The client  id to access the keyVault
     * @param keyVaultClientSecret The client secret to access the keyVault
     * @param keyVaultTenantId The tenant id to access the keyVault
     * @return an updated object
     */
    public ServicePrincipalInKeyVaultCredentialEntity setKeyVaultForDataSourceSecrets(String keyVaultEndpoint,
                                                                                      String keyVaultClientId,
                                                                                      String keyVaultClientSecret,
                                                                                      String keyVaultTenantId) {
        return this;
    }

    /**
     * Sets the name of the keyvault secret holding client id.
     *
     * @param clientIdSecretName The secret name
     * @return an updated object with client id secret name set
     */
    public ServicePrincipalInKeyVaultCredentialEntity setSecretNameForDataSourceClientId(String clientIdSecretName) {
        return this;
    }

    /**
     * Sets the name of the keyvault secret holding client secret.
     *
     * @param clientSecretName The secret name
     * @return an updated object with client secret name set
     */
    public ServicePrincipalInKeyVaultCredentialEntity setSecretNameForDataSourceClientSecret(String clientSecretName) {
        return this;
    }

    /**
     * Sets the tenant id.
     *
     * @param tenantId The tenant id
     * @return an updated object with client tenant id set
     */
    public ServicePrincipalInKeyVaultCredentialEntity setDataSourceTenantId(String tenantId) {
        return this;
    }

    /**
     * Sets the description.
     *
     * @param description The description
     * @return an updated object with description set
     */
    public ServicePrincipalInKeyVaultCredentialEntity setDescription(String description) {
        return this;
    }
}
