// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor.models;

/**
 * The service principal credential entity for data source..
 */
public final class ServicePrincipalCredentialEntity extends DataSourceCredentialEntity {
    @Override
    public String getId() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }

    /**
     * Gets the client id.
     *
     * @return The client id.
     */
    public String getClientId() {
        return null;
    }

    /**
     * Gets the tenant id.
     *
     * @return The tenant id.
     */
    public String getTenantId() {
        return null;
    }

    /**
     * Creates ServicePrincipalCredentialEntity.
     *
     * @param name The name.
     * @param clientId The client id.
     * @param clientSecret The client secret.
     * @param tenantId The teant id.
     */
    public ServicePrincipalCredentialEntity(String name, String clientId, String clientSecret, String tenantId) {

    }

    /**
     * Sets the name.
     *
     * @param name The name
     * @return an updated object with name set
     */
    public ServicePrincipalCredentialEntity setName(String name) {
        return this;
    }

    /**
     * Sets the client id.
     *
     * @param clientId The client id
     * @return an updated object with client id set
     */
    public ServicePrincipalCredentialEntity setClientId(String clientId) {
        return this;
    }

    /**
     * Sets the client secret.
     *
     * @param clientSecret The client secret
     * @return an updated object with client secret set
     */
    public ServicePrincipalCredentialEntity setClientSecret(String clientSecret) {
        return this;
    }

    /**
     * Sets the tenant id.
     *
     * @param tenantId The tenant id
     * @return an updated object with client teant id set
     */
    public ServicePrincipalCredentialEntity setTenantId(String tenantId) {
        return this;
    }

    /**
     * Sets the description.
     *
     * @param description The description
     * @return an updated object with description set
     */
    public ServicePrincipalCredentialEntity setDescription(String description) {
        return this;
    }
}
