// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor.models;

import com.azure.ai.metricsadvisor.implementation.util.Option;
import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The ServicePrincipalParamPatch model. */
@Fluent
public final class ServicePrincipalParamPatch {
    /*
     * The client id of the service principal.
     */
    @JsonProperty(value = "clientId")
    private Option<String> clientId;

    /*
     * The client secret of the service principal.
     */
    @JsonProperty(value = "clientSecret")
    private Option<String> clientSecret;

    /*
     * The tenant id of the service principal.
     */
    @JsonProperty(value = "tenantId")
    private Option<String> tenantId;

    /**
     * Get the clientId property: The client id of the service principal.
     *
     * @return the clientId value.
     */
    String getClientId() {
        if (this.clientId != null) {
            this.clientId.getValue();
        }
        return null;
    }

    /**
     * Set the clientId property: The client id of the service principal.
     *
     * @param clientId the clientId value to set.
     * @return the ServicePrincipalParamPatch object itself.
     */
    public ServicePrincipalParamPatch setClientId(String clientId) {
        if (clientId == null) {
            this.clientId = Option.empty();
        } else {
            this.clientId = Option.of(clientId);
        }
        return this;
    }

    /**
     * Get the clientSecret property: The client secret of the service principal.
     *
     * @return the clientSecret value.
     */
    String getClientSecret() {
        if (this.clientSecret != null) {
            this.clientSecret.getValue();
        }
        return null;
    }

    /**
     * Set the clientSecret property: The client secret of the service principal.
     *
     * @param clientSecret the clientSecret value to set.
     * @return the ServicePrincipalParamPatch object itself.
     */
    public ServicePrincipalParamPatch setClientSecret(String clientSecret) {
        if (clientSecret == null) {
            this.clientSecret = Option.empty();
        } else {
            this.clientSecret = Option.of(clientSecret);
        }
        return this;
    }

    /**
     * Get the tenantId property: The tenant id of the service principal.
     *
     * @return the tenantId value.
     */
    String getTenantId() {
        if (this.tenantId != null) {
            this.tenantId.getValue();
        }
        return null;
    }

    /**
     * Set the tenantId property: The tenant id of the service principal.
     *
     * @param tenantId the tenantId value to set.
     * @return the ServicePrincipalParamPatch object itself.
     */
    public ServicePrincipalParamPatch setTenantId(String tenantId) {
        if (tenantId == null) {
            this.tenantId = Option.empty();
        } else {
            this.tenantId = Option.of(tenantId);
        }
        return this;
    }
}
