// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor.models;

/**
 * The sql connection credential entity for DataLakeGen2.
 */
public final class SQLServerConnectionStringCredentialEntity extends DataSourceCredentialEntity {
    @Override
    public String getId() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }

    /**
     * Creates SQLServerConnectionStringCredentialEntity.
     *
     * @param name The name
     * @param connectionString The connection string
     */
    public SQLServerConnectionStringCredentialEntity(String name, String connectionString) {
    }

    /**
     * Sets the connection string.
     *
     * @param connectionString The connection string
     * @return an updated object with connection string set
     */
    public SQLServerConnectionStringCredentialEntity setConnectionString(String connectionString) {
        return this;
    }

    /**
     * Sets the description.
     *
     * @param description The description.
     * @return an updated object with description set
     */
    public SQLServerConnectionStringCredentialEntity setDescription(String description) {
        return this;
    }
}
