// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor.models;

import com.azure.ai.metricsadvisor.implementation.util.Option;
import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** The WebhookHookInfoPatch model. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "hookType")
@JsonTypeName("Webhook")
@Fluent
public final class WebhookHookInfoPatch extends HookInfoPatch {
    /*
     * The hookParameter property.
     */
    @JsonProperty(value = "hookParameter")
    private Option<WebhookHookParameterPatch> hookParameter;

    /**
     * Get the hookParameter property: The hookParameter property.
     *
     * @return the hookParameter value.
     */
    WebhookHookParameterPatch getHookParameter() {
        if (this.hookParameter != null) {
            this.hookParameter.getValue();
        }
        return null;
    }

    /**
     * Set the hookParameter property: The hookParameter property.
     *
     * @param hookParameter the hookParameter value to set.
     * @return the WebhookHookInfoPatch object itself.
     */
    public WebhookHookInfoPatch setHookParameter(WebhookHookParameterPatch hookParameter) {
        if (hookParameter == null) {
            this.hookParameter = Option.empty();
        } else {
            this.hookParameter = Option.of(hookParameter);
        }
        return this;
    }
}
